name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.3.1
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_KEY }}
          host_fingerprint: ${{ secrets.VM_FINGERPRINT }}
          command: cd /var/www/html/esp32-web && git pull
          
