name: Auto Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          connect_timeout: 30s
          first_ssh: |
            whoami
            hostname
            cd /var/www/html/esp32-web
            git pull
